name: Publish PKG

on:
  push:
    branches: master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # ensure GITHUB_TOKEN has write access
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm ci
      - run: npm pkg fix
      - run: npm adduser
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
